FROM apache/flink:2.0-scala_2.12

# Install connector dependencies
USER root

# Download the Kafka connector JAR
RUN curl -fSL \
    -o /opt/flink/lib/flink-sql-connector-kafka-4.0.0-2.0.jar \
    https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.0-2.0/flink-sql-connector-kafka-4.0.0-2.0.jar

# JSON format factory
RUN curl -fSL \
    -o /opt/flink/lib/flink-json-2.0.0.jar \
    https://repo1.maven.org/maven2/org/apache/flink/flink-json/2.0.0/flink-json-2.0.0.jar

# Prometheus metrics reporter
# RUN curl -fSL \
#     -o /opt/flink/lib/flink-metrics-prometheus-2.0.0.jar \
#     https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus/2.0.0/flink-metrics-prometheus-2.0.0.jar

USER flink