services:
  ingestion:
    env_file: .env.test
    build:
      target: test
    profiles:
      - unit-tests

  processing:
    env_file: .env.test
    build:
      target: test
    profiles:
      - unit-tests

  storage:
    env_file: .env.test

  cache:
    env_file: .env.test

  # Integration and E2E test runner
  test-runner:
    env_file:
      - .env.test
    build:
      context: ../../tests
      dockerfile: Dockerfile
    volumes:
      - ../../services:/app/services:ro
      - ../../tests:/tests:ro
      - ../../coverage-reports:/coverage-reports
    environment:
      - PYTHONPATH=/app
    depends_on:
      kafka1:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      ingestion:
        condition: service_started
      processing:
        condition: service_started
      storage:
        condition: service_started
    networks:
      - analytics_net
    profiles:
      - integration-tests
      - e2e-tests
