services:
  ingestion:
    env_file: .env.test
    build:
      target: test
    environment:
      UVICORN_WORKERS: ${UVICORN_WORKERS:-40}
      UVICORN_BACKLOG: ${UVICORN_BACKLOG:-8192}
      UVICORN_KEEP_ALIVE: ${UVICORN_KEEP_ALIVE:-300}
    volumes:
      - ../../coverage-reports/ingestion:/app/coverage

  processing:
    env_file: .env.test
    build:
      target: test
    volumes:
      - ../../coverage-reports/processing:/app/coverage

  storage:
    env_file: .env.test

  cache:
    env_file: .env.test
    build:
      target: test
    volumes:
      - ../../coverage-reports/cache:/app/coverage

  # Integration and E2E test runner
  test-runner:
    env_file:
      - .env.test
    build:
      context: ../../tests
      dockerfile: Dockerfile
    volumes:
      - ../../services:/app/services:ro
      - ../../tests:/tests:ro
      - ../../coverage-reports/integration:/app/coverage-reports
      - ../../coverage-reports/perf-results:/app/perf-results
    environment:
      - PYTHONPATH=/app
      - PERF_RESULTS_DIR=/app/perf-results
    depends_on:
      kafka1:
        condition: service_healthy
      clickhouse:
        condition: service_started
      ingestion:
        condition: service_started
      processing:
        condition: service_started
      storage:
        condition: service_started
      cache:
        condition: service_started
    networks:
      - analytics_net
