services:
  processing:
    env_file: .env.test

  storage:
    env_file: .env.test

  test-runner:
    env_file:
      - .env.test
    build:
      context: ../../tests
      dockerfile: Dockerfile
    volumes:
      - ../../services:/app/services:ro
      - ../../tests:/tests:ro
    depends_on:
      - ingestion
      - processing
      - storage
    networks:
      - analytics_net

networks:
  analytics_net:
    driver: bridge
    name: analytics_net_test
