services:
  ingestion:
    env_file: .env.test

  processing:
    env_file: .env.test

  storage:
    env_file: .env.test

  # Unit test services - isolated test containers for each service
  ingestion-test:
    build:
      context: ../../services/ingestion
      dockerfile: Dockerfile
      target: test
    volumes:
      - ../../services/ingestion:/app
      - ../../coverage-reports:/coverage-reports
    environment:
      - PYTHONPATH=/app
      - COVERAGE_FILE=/coverage-reports/.coverage_ingestion
    working_dir: /app
    networks:
      - analytics_net
    profiles:
      - unit-tests

  processing-test:
    build:
      context: ../../services/processing
      dockerfile: Dockerfile.processing
      target: test
    volumes:
      - ../../services/processing:/app
      - ../../coverage-reports:/coverage-reports
    environment:
      - PYTHONPATH=/app
      - COVERAGE_FILE=/coverage-reports/.coverage_processing
    working_dir: /app
    networks:
      - analytics_net
    profiles:
      - unit-tests

  # Integration and E2E test runner
  test-runner:
    env_file:
      - .env.test
    build:
      context: ../../tests
      dockerfile: Dockerfile
    volumes:
      - ../../services:/app/services:ro
      - ../../tests:/tests:ro
      - ../../coverage-reports:/coverage-reports
    environment:
      - PYTHONPATH=/app
    depends_on:
      kafka1:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      ingestion:
        condition: service_started
      processing:
        condition: service_started
      storage:
        condition: service_started
    networks:
      - analytics_net
    profiles:
      - integration-tests
      - e2e-tests
