global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flink"
    static_configs:
      - targets: ["jobmanager:9249"]

  - job_name: "ingestion"
    static_configs:
      - targets: ["ingestion:8000"]

  - job_name: "storage"
    static_configs:
      - targets: ["storage:8001"]
