global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flink"
    static_configs:
      - targets: ["jobmanager:9249"]

  # Add this new job
  - job_name: "ingestion-api"
    static_configs:
      - targets: ["ingestion:8000"]