global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flink"
    static_configs:
      - targets: ["jobmanager:9249"]

  - job_name: "processing"
    static_configs:
      - targets: ["taskmanager1:9250", "taskmanager2:9250"]

  - job_name: "ingestion"
    static_configs:
      - targets: ["ingestion:8000"]

  - job_name: "storage"
    static_configs:
      - targets: ["storage:8001"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka1:7071"]
